version: "3.2"
services:
  python:
    build: .
    volumes:
      - app:/usr/src/app
    ports:
      - ${HTTP_PORT}:80
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    networks:
      - php_network
    extra_hosts:
      - "hello:172.31.0.6"

volumes:
  app:
    driver_opts:
      type: none
      device: ${PWD}/app
      o: bind
networks:
  php_network:
    name: php_network

